### PR TITLE
US1: Remove limitation on the number of messages allowed to be send in a minute

### LINKED ISSUE #9: US1: Remove limitation on the number of messages allowed to be send in a minute (Backend logic)

### LINKED ISSUE #10: US1: Remove limitation on the number of messages allowed to be send in a minute (UI: remove the error message indicating too many messages was sent)

### PR DESCRIPTION
**Pull request by ThomasJXiao**
**Update:**
Removed 2 test functions that tests message flooding prevention, We removed these tests because as this user story is trying to disable the message rate limit in chats.

The tests are in the test/messaging.js file. Here are the following test. 

image

image

**Description:**
Removed the limit on the number of messages that are allowed to be sent within a minute.
Removed the error message after a user tried to send multiple messages within a minute.  
Fixes https://github.com/CMU-313/nodebb-f24-cmu-secure/issues/9
Fixes https://github.com/CMU-313/nodebb-f24-cmu-secure/issues/10

**What Has Been Changed:**
Now if someone is logged into their Nodebb account and has chosen someone to chat with, when they send multiple messages in any chat within a minute, then all messages should be delivered without any delay or constraints.
Now if someone is part of a chat with multiple members, when they send multiple messages in rapid succession, then each message should appear in the correct order on the recipients' screens.
Now if someone sends multiple messages within a minute, when the messages contain different content (text, links, emojis, or attachments), then all message types should be sent successfully without constraints.
Now if someone sends multiple messages rapidly, when the messages are sent within a one-minute window, then there should be no error message or warning indicating a rate limit has been reached.
Code Changes :

• Modified Config.json, src/api/chats.js, src/middleware/ratelimit.js
Modified rateLimitExceeded function in chat.js
image

* Modified isFlooding function in ratelimit.js
image

**Testing:**

Tested & Verified that the user are allowed to send multiple message within a minutes into a direct messages chat and group chats
Tested & Verified that the error message for limiting the amount of message sent is not visible after multiple message are sent within a minute

### CODE REVIEW

**Review by tanoctavius — CHANGES_REQUESTED** [review]
The changes look good and make sense! However, the lint tests need to be passed before it can be merged.

**Review by gpxxlt — COMMENTED** [review]
The deletion is quite self-explanatory, and will be better if there are some comments.

**Review by Akshra-school — CHANGES_REQUESTED** [review]
The code changes look good but make sure the lint tests pass before merging!

**Comment by ThomasJXiao** [comment]
US1: Remove limitation on the number of messages allowed to be send in a minute


**Description:**
Removed the limit on the number of messages that are allowed to be sent within a minute.
Removed the error message after a user tried to send multiple messages within a minute.  
Fixes #9 
Fixes #10 
**What Has Been Changed:**
* Now if someone is logged into their Nodebb account and has chosen someone to chat with, when they send multiple messages in any chat within a minute, then all messages should be delivered without any delay or constraints.
* Now if someone is part of a chat with multiple members, when they send multiple messages in rapid succession, then each message should appear in the correct order on the recipients' screens.
* Now if someone sends multiple messages within a minute, when the messages contain different content (text, links, emojis, or attachments), then all message types should be sent successfully without constraints.
* Now if someone sends multiple messages rapidly, when the messages are sent within a one-minute window, then there should be no error message or warning indicating a rate limit has been reached.
**Code Changes** : 	
•	Modified Config.json, src/api/chats.js, src/middleware/ratelimit.js
    * Modified rateLimitExceeded function in chat.js

	
Pasted Graphic



    * Modified isFlooding function in ratelimit.js

ratelimit isFlooding = function (socket) €



**Testing:**
* Tested & Verified that the user are allowed to send multiple message within a minutes into a direct messages chat and group chats
* Tested & Verified that the error message for limiting the amount of message sent is not visible after multiple message are sent within a minute
* All UX testing is now working


**Comments on not passing the lint test**:

-   The test that is not passing on this PR is the following test:
       rooms
         should return rate limit error on second try:

      AssertionError [ERR_ASSERTION]: 200 == 400
      + expected - actual

      -200
      +400
      
      at Context.<anonymous> (test/messaging.js:165:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**We are not going to try to fix this lint test error, as this user story is trying to disable the message rate limit in chats. It would be counterintuitive for us to pass this lint test.**

**Review by tanoctavius — APPROVED** [review]
The lint tests works so its all good!

**Comment by ThomasJXiao** [comment]
> The code changes look good but make sure the lint tests pass before merging!

Fixed. Check the newest code for reference.

**Review by Akshra-school — APPROVED** [review]
It looks like you fixed your tests and removed code that was nonessential. Great work!

**Review by gpxxlt — APPROVED** [review]
Impressive work to get all tests passed!

**Pull request merged**
