### PR TITLE
US4: Completed back-end logic for "Endorse Topic" button that appears upon clicking the "Topic Tools" drop-down menu

### LINKED ISSUE #15: US4: [Backend] Configure new attribute "endorsed" in the database and implement back-end functions that enable "endorse" functionality
### Details
For each response in the database, add another attribute `endorsed` that indicates whether a response is endorsed or not (a `boolean` field). The default value will be `false`. People with admin accounts can modify the value either through admin site, or clicking on buttons that are only visible and functional when logged into an admin account.
### Acceptance Criteria
1. Answers that are not endorsed should not be marked as endorsed, and vice versa.
2. Students (or anyone without an admin account) cannot modify the state of an answer being endorsed or not; but instructors can.

### PR DESCRIPTION
**Pull request by gpxxlt**
#### What Has Been Changed:
1. As the topic has mentioned, the newly implemented back-end functions and logic enable an "Endorse Topic" button that appears upon clicking the "Topic Tools" drop-down menu, and the button can correctly switch between states "Endorse" and "Unendorse." Note that the actual UI is not properly rendering these two words, but the functionality is there.
2. Just like all other topic tools that will log info after action, a message will appear at the end of the logging board of the topic. Unfortunately, only back-end logic has been successfully, so the message contains some weird info. See below images for illustration.

#### Testing:
Testing is by far mainly tested through `console.log()` and UI testing. Though there are no test cases, errors are handled just like all other error handlers in the codebase. Thorough test cases are still under construction, and will be implemented when the front-end part of this function is complete.

#### Next Sprint Todos:
- [ ] After finishing front-end logic, construct test cases that ensure correctness and safety of this feature.
- [ ] Implement endorse logic for posts, not just topics.

### CODE REVIEW

**Review by tanoctavius — COMMENTED** [review]
The tools.js section looks good! The logic behind the Endorsement state and buttons also make sense.

**Review by Akshra-school — CHANGES_REQUESTED** [review]
Be sure to address check failures!

**Review by ThomasJXiao — DISMISSED** [review]
This is great work. Be sure to address check failures.

**Review by ThomasJXiao — COMMENTED** [review]
This is good work. Be sure to address check failures!

**Review by ThomasJXiao — COMMENTED** [review]
This is good work. Be sure to address check failures coming up.

**Comment by gpxxlt** [comment]
Unable to merge this pull request for now due to test failure. There is only one failed test case. From the error message, it seems that the response body does not match a pre-defined schema. This could be the case that I did no change the schema to fit the new feature. I am still working on this right now, and unfortunately cannot merge this request in the first sprint.

**Review by tanoctavius — COMMENTED** [review]
All of the work done looks great! Since all of the lint tests are passing, it is ready to be merged into the main line.

**Review by ThomasJXiao — APPROVED** [review]
This is great work YG. You added a lot great work.

**Review by Akshra-school — APPROVED** [review]
This code looks good! It properly adds the backend logic for endorsement.

**Review by tanoctavius — APPROVED** [review]
Looks great! The logic makes sense

**Pull request merged**
